### ISSUE TITLE
Make this repository public

### ISSUE THREAD

**Issue by philwills** [guardian/recommendations#13]
I think this has been around long enough and bedded down enough that we should be OK with making it public. Are there any reasons why we shouldn't?

cc @tackley

**Comment by philwills** [comment]
Done.

**Comment by tackley** [comment]
[replying to this to try to understand why I got a notification about it]

> On 23 Oct 2015, at 14:48, Phil Wills <notifications@github.com> wrote:
> 
> Done.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/guardian/recommendations/issues/13#issuecomment-150578152>.
> 


-- 

------------------------------
This e-mail and all attachments are confidential and may also be 
privileged. If you are not the named recipient, please notify the sender 
and delete the e-mail and all attachments immediately. Do not disclose the 
contents to another person. You may not use the information for any 
purpose, or store, or copy, it in any way.  Guardian News & Media Limited 
is not liable for any computer viruses or other material transmitted with 
or as part of this e-mail. You should employ virus checking software.
 
Guardian News & Media Limited is a member of Guardian Media Group plc. Registered 
Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered 
in England Number 908396

**Comment by philwills** [comment]
I had cc'd you when I opened the issue asking about it, though you never
replied.

On Wed, 28 Oct 2015 at 11:15 Graham Tackley <notifications@github.com>
wrote:

> [replying to this to try to understand why I got a notification about it]
>
> > On 23 Oct 2015, at 14:48, Phil Wills <notifications@github.com> wrote:
> >
> > Done.
> >
> > —
> > Reply to this email directly or view it on GitHub <
> https://github.com/guardian/recommendations/issues/13#issuecomment-150578152
> >.
> >
>
>
> --
>
> ------------------------------
> This e-mail and all attachments are confidential and may also be
> privileged. If you are not the named recipient, please notify the sender
> and delete the e-mail and all attachments immediately. Do not disclose the
> contents to another person. You may not use the information for any
> purpose, or store, or copy, it in any way. Guardian News & Media Limited
> is not liable for any computer viruses or other material transmitted with
> or as part of this e-mail. You should employ virus checking software.
>
> Guardian News & Media Limited is a member of Guardian Media Group plc.
> Registered
> Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.
> Registered
> in England Number 908396
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/guardian/recommendations/issues/13#issuecomment-151791123>
> .
>

-- 

------------------------------
This e-mail and all attachments are confidential and may also be 
privileged. If you are not the named recipient, please notify the sender 
and delete the e-mail and all attachments immediately. Do not disclose the 
contents to another person. You may not use the information for any 
purpose, or store, or copy, it in any way.  Guardian News & Media Limited 
is not liable for any computer viruses or other material transmitted with 
or as part of this e-mail. You should employ virus checking software.
 
Guardian News & Media Limited is a member of Guardian Media Group plc. Registered 
Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered 
in England Number 908396
