### ISSUE TITLE
resiliency

### ISSUE THREAD

**Issue by davidfurey** [guardian/recommendations#28]
The resilience levels in resiliency.md are interesting, but is this structure something we use?  If we do, then great.  Otherwise I think we should either start using it or delete it.  Thoughts?

**Comment by philwills** [comment]
No, I don't think it's something we ever fully adopted. I think it's good to define that there are different concerns which are applicable for different services, but I'd agree that this doesn't represent reality. I'd rather replace than delete, but maybe that's a sensible first step.
